algoritmo "idade"
// Função :
// Autor :
// Data : 03/05/2014
// Seção de Declarações 
var
   idade:inteiro
inicio
   Escreva("Digite sua idade:")
   Leia(idade)
   Se idade<=0 Entao
      Escreva("Invalido")
   Senao
      Se idade<18 Entao
         Escreva("Nao maioridade")
      Senao
         Se idade>=18 Entao
            Escreva("Maioridade")
         Senao
         fimse
      fimse
   fimse
fimalgoritmo
