/*******************************************
          Criando as novas tabelas
*******************************************/
CREATE TABLE REGIAO (
	COD_REGIAO	NUMBER	NOT NULL,
	NOM_REGIAO	VARCHAR2(100) NOT NULL,
	PRIMARY KEY (COD_REGIAO)
);

CREATE TABLE UNIDADE_FEDERATIVA (
  SIGLA_UF 						VARCHAR2(2) 		NOT NULL,
  NOME_UF 						VARCHAR2(100),
  PRIMARY KEY(SIGLA_UF)
);

CREATE TABLE CONDICOESPAGAMENTO (
  CODCONDPGTO 					NUMBER  				NOT NULL,
  DSCCONDPGTO 					VARCHAR2(100),
  IDFTIPOCONDPGTO 			NUMBER 				DEFAULT 0,
  IDFATIVO 						VARCHAR2(1) 		DEFAULT 'S',
  PRIMARY KEY(CODCONDPGTO)
);

CREATE TABLE UNIDADE (
  CODUNIDADE 					NUMBER  				NOT NULL,
  DSCUNIDADE 					VARCHAR2(16),
  IDFATIVO 	 					VARCHAR2(1) 		DEFAULT 'S',
  PRIMARY KEY(CODUNIDADE)
);

CREATE TABLE CONTA (
  NUMCONTA 						NUMBER 				NOT NULL,
  DSCCONTA 						VARCHAR2(250), 	
  IDFMOVIMENTOCONTA 			VARCHAR2(1) 		DEFAULT 'C',
  IDFATIVO 						VARCHAR2(1) 		DEFAULT 'S',
  PRIMARY KEY(NUMCONTA)                   	
);                                        	
                                          	
CREATE TABLE AMBIENTE (                   	
  CODAMBIENTE 					NUMBER  				NOT NULL,
  DSCAMBIENTE 					VARCHAR2(50) 		NOT NULL,
  IDFATIVO 						VARCHAR2(1) 		DEFAULT 'A',
  PRIMARY KEY(CODAMBIENTE)                	
);                                        	
                                          	
CREATE TABLE CATEGORIA (                  	
  CODCATEGORIA 				NUMBER  				NOT NULL,
  DSCCATEGORIA 				VARCHAR2(250), 	
  IDFATIVO 						VARCHAR2(1) 		DEFAULT 'A',
  PRIMARY KEY(CODCATEGORIA)
);

CREATE TABLE CLASSIFICACAOPESSOA (
  CODCLASSIFICACAOPESSOA 	NUMBER  				NOT NULL,
  DSCCLASSIFICACAOPESSOA 	VARCHAR2(50),
  IDFATIVO 						VARCHAR2(1) 		DEFAULT 'S',
  PRIMARY KEY(CODCLASSIFICACAOPESSOA)
);

CREATE TABLE MESA (
  CODMESA 						NUMBER  				NOT NULL,
  CODAMBIENTE 					NUMBER  				NOT NULL,
  QTDELUGARESMESA 			NUMBER,
  IDFSITUACAO 					VARCHAR2(1) 		DEFAULT 'L',
  PRIMARY KEY(CODMESA),
  FOREIGN KEY(CODAMBIENTE) 				REFERENCES AMBIENTE(CODAMBIENTE)
);

CREATE TABLE CIDADE (
  CODCIDADE 					NUMBER  				NOT NULL,
  SIGLA_UF 						VARCHAR2(2) 		NOT NULL,
  NOMCIDADE 					VARCHAR2(150),
  PRIMARY KEY(CODCIDADE),
  FOREIGN KEY(SIGLA_UF) 					REFERENCES UNIDADE_FEDERATIVA(SIGLA_UF)
);

CREATE TABLE CONDICOESPAGAMENTOPRAZOS (
  CODCONDPGTO 					NUMBER  				NOT NULL,
  NUMDIASCODPGTO 				NUMBER  				NOT NULL,
  PRIMARY KEY(CODCONDPGTO, NUMDIASCODPGTO),
  FOREIGN KEY(CODCONDPGTO) 				REFERENCES CONDICOESPAGAMENTO(CODCONDPGTO)
);

CREATE TABLE PRODUTO (
  CODPRODUTO 					NUMBER  				NOT NULL,
  CODCATEGORIA 				NUMBER  				NOT NULL,
  CODUNIDADE 					NUMBER  				NOT NULL,
  NOMPRODUTO 					VARCHAR2(250),
  PCOVDAPRODUTO 				DECIMAL(10,2),
  IDFATIVO 						VARCHAR2(1),
  PRIMARY KEY(CODPRODUTO),
  FOREIGN KEY(CODUNIDADE) 	 				REFERENCES UNIDADE(CODUNIDADE),
  FOREIGN KEY(CODCATEGORIA) 				REFERENCES CATEGORIA(CODCATEGORIA)
);

CREATE TABLE CONVERSAOUNIDADE (
  CODUNIDADE 					NUMBER  				NOT NULL,
  CODUNIDADECONVERTIDA 		NUMBER  				NOT NULL,
  QTDCONVERSAO 				DECIMAL(10,2) 		NOT NULL,
  IDFATIVO 						VARCHAR2(1) 		DEFAULT 'S',
  PRIMARY KEY(CODUNIDADE, CODUNIDADECONVERTIDA),
  FOREIGN KEY(CODUNIDADE) 					REFERENCES UNIDADE(CODUNIDADE),
  FOREIGN KEY(CODUNIDADECONVERTIDA) 	REFERENCES UNIDADE(CODUNIDADE)
);

CREATE TABLE PESSOA (
  CODPESSOA 					NUMBER  				NOT NULL,
  CODCLASSIFICACAOPESSOA 	NUMBER  				NOT NULL,
  CODCIDADE 					NUMBER  				NOT NULL,
  NOMPESSOA 					VARCHAR2(250),
  ENDPESSOA 					VARCHAR2(250),
  NUMPESSOA 					VARCHAR2(10),
  COMPESSOA 					VARCHAR2(20),
  IDFSITUACAO 					VARCHAR2(1) 		DEFAULT 'A',
  PRIMARY KEY(CODPESSOA),
  FOREIGN KEY(CODCIDADE) 					REFERENCES CIDADE(CODCIDADE),
  FOREIGN KEY(CODCLASSIFICACAOPESSOA) 	REFERENCES CLASSIFICACAOPESSOA(CODCLASSIFICACAOPESSOA)
);

CREATE TABLE PRODUTOCOMPOSTO (
  CODPRODUTO 					NUMBER  				NOT NULL,
  CODPRODUTOPOR 				NUMBER  				NOT NULL,
  CODUNIDADE 					NUMBER  				NOT NULL,
  IDFATIVO 						VARCHAR2(1) 		DEFAULT 'S',
  PRIMARY KEY(CODPRODUTO, CODPRODUTOPOR),
  FOREIGN KEY(CODPRODUTO) 					REFERENCES PRODUTO(CODPRODUTO),
  FOREIGN KEY(CODPRODUTOPOR) 				REFERENCES PRODUTO(CODPRODUTO),
  FOREIGN KEY(CODUNIDADE) 					REFERENCES UNIDADE(CODUNIDADE)
);

CREATE TABLE PESSOAJURIDICA (
  CODPESSOA 					NUMBER  				NOT NULL,
  INSCPESSOA 					VARCHAR2(16),
  CNPJPESSOA 					VARCHAR2(16),
  PRIMARY KEY(CODPESSOA),
  FOREIGN KEY(CODPESSOA) 					REFERENCES PESSOA(CODPESSOA)
);

CREATE TABLE PESSOAFISICA (
  CODPESSOA 					NUMBER  				NOT NULL,
  RGPESSOA 						VARCHAR2(16),
  CPFPESSOA 					VARCHAR2(16),
  IDFSEXO 						VARCHAR2(1) 		NOT NULL,
  PRIMARY KEY(CODPESSOA),
  FOREIGN KEY(CODPESSOA) 					REFERENCES PESSOA(CODPESSOA)
);

CREATE TABLE PRODUTOEXTERNO (
  CODPRODUTO 					NUMBER  				NOT NULL,
  CODUNIDADE 					NUMBER  				NOT NULL,
  QTDESTATUALPRODUTO 		DECIMAL(10,2),
  QTDEESTMINPRODUTO 			DECIMAL(10,2),
  QTDEESTMAXPRODUTO 			DECIMAL(10,2),
  QTDEPONTOPEDPRODUTO 		DECIMAL(10,2),
  PRIMARY KEY(CODPRODUTO),
  FOREIGN KEY(CODPRODUTO) 					REFERENCES PRODUTO(CODPRODUTO),
  FOREIGN KEY(CODUNIDADE) 					REFERENCES UNIDADE(CODUNIDADE)
);                               		

CREATE TABLE RESERVA (
  NUMRESERVA 					NUMBER  				NOT NULL,
  CODPESSOA 					NUMBER  				NOT NULL,
  DTAINIRESERVA 				DATE,
  DTAFIMRESERVA 				DATE,
  NUMLUGARES 					NUMBER,
  CODPESSOAATEND 				NUMBER  				NOT NULL,
  VLRGARCON 					DECIMAL(10,2),
  IDFSITUACAO 					VARCHAR2(1) 		DEFAULT 'R',
  PRIMARY KEY(NUMRESERVA),
  FOREIGN KEY(CODPESSOA) 					REFERENCES PESSOA(CODPESSOA),
  FOREIGN KEY(CODPESSOAATEND) 			REFERENCES PESSOA(CODPESSOA)
);

CREATE TABLE MESASRESERVA (
  NUMRESERVA 					NUMBER  				NOT NULL,
  CODMESA 						NUMBER  				NOT NULL,
  IDFSITUACAO 					VARCHAR2(1) 		DEFAULT 'R',
  PRIMARY KEY(NUMRESERVA, CODMESA),
  FOREIGN KEY(NUMRESERVA)  				REFERENCES RESERVA(NUMRESERVA),
  FOREIGN KEY(CODMESA)    					REFERENCES MESA(CODMESA)
);

CREATE TABLE FORNECEDORPRODUTO (
  CODPESSOA 					NUMBER  				NOT NULL,
  CODPRODUTO 					NUMBER  				NOT NULL,
  PCOCOMPRA 					DECIMAL(10,2),
  PRIMARY KEY(CODPESSOA, CODPRODUTO),
  FOREIGN KEY(CODPESSOA) 					REFERENCES PESSOA(CODPESSOA),
  FOREIGN KEY(CODPRODUTO) 					REFERENCES PRODUTO(CODPRODUTO)
);

CREATE TABLE PEDIDOCOMPRA (
  NUMPEDIDOCOMPRA 			NUMBER  				NOT NULL,
  CODCONDPGTO 					NUMBER  				NOT NULL,
  CODPESSOA 					NUMBER  				NOT NULL,
  DTAPEDIDOCOMPRA 			DATE 					DEFAULT SYSDATE,
  IDFSITUACAO 					VARCHAR2(1) 		DEFAULT 'A',
  PRIMARY KEY(NUMPEDIDOCOMPRA),
  FOREIGN KEY(CODPESSOA) 					REFERENCES PESSOA(CODPESSOA),
  FOREIGN KEY(CODCONDPGTO)					REFERENCES CONDICOESPAGAMENTO(CODCONDPGTO)
);

CREATE TABLE PESSOAATENDE (
  CODMESA 						NUMBER  				NOT NULL,
  CODPESSOA 					NUMBER  				NOT NULL,
  FOREIGN KEY(CODPESSOA) 					REFERENCES PESSOA(CODPESSOA),
  FOREIGN KEY(CODMESA)   					REFERENCES MESA(CODMESA)
);

CREATE TABLE CONSUMO (
  NUMCONSUMO 					NUMBER  				NOT NULL,
  CODPRODUTO 					NUMBER  				NOT NULL,
  NUMRESERVA 					NUMBER  				NOT NULL,
  CODPESSOA  					NUMBER  				NOT NULL,
  QTDECONSUMO 					DECIMAL(10,2),
  PCOCONSUMO 					DECIMAL(10,2),
  PRIMARY KEY(NUMCONSUMO),
  FOREIGN KEY(CODPESSOA) 					REFERENCES PESSOA(CODPESSOA),
  FOREIGN KEY(NUMRESERVA)					REFERENCES RESERVA(NUMRESERVA),
  FOREIGN KEY(CODPRODUTO)  				REFERENCES PRODUTO(CODPRODUTO)
);

CREATE TABLE TITULO (
  NUMTITULO 					NUMBER  				NOT NULL,
  NUMCONTA 						NUMBER  				NOT NULL,
  NUMPEDIDOCOMPRA 			NUMBER  				NOT NULL,
  CODPESSOA 					NUMBER  				NOT NULL,
  DSCTITULO 					VARCHAR2(250),
  VLRTITULO 					DECIMAL(10,2),
  IDFMOVTOTITULO 				VARCHAR2(1) 		DEFAULT 'C',
  PRIMARY KEY(NUMTITULO),
  FOREIGN KEY(CODPESSOA) 					REFERENCES PESSOA(CODPESSOA),
  FOREIGN KEY(NUMPEDIDOCOMPRA)			REFERENCES PEDIDOCOMPRA(NUMPEDIDOCOMPRA),
  FOREIGN KEY(NUMCONTA) 					REFERENCES CONTA(NUMCONTA)
);

CREATE TABLE TITULOPAGAR (
  NUMTITULO 					NUMBER  				NOT NULL,
  DTAPGTOTITULO 				DATE 					NOT NULL,
  VLRPGTOTITULO 				DECIMAL(10,2),
  PRIMARY KEY(NUMTITULO),
  FOREIGN KEY(NUMTITULO) 					REFERENCES TITULO(NUMTITULO)
);

CREATE TABLE TITULORECEBER (
  NUMTITULO 					NUMBER  				NOT NULL,
  DTARECBTOTITULO 			DATE,
  VLRRECBTOTITULO 			DECIMAL(10,2),
  PRIMARY KEY(NUMTITULO),
  FOREIGN KEY(NUMTITULO)					REFERENCES TITULO(NUMTITULO)
);

CREATE TABLE PRODUTOSPEDIDOCOMPRA (
  NUMPEDIDOCOMPRA 			NUMBER  				NOT NULL,
  CODPRODUTO 					NUMBER  				NOT NULL,
  QTDEPRODUTO 					NUMBER,
  PCOCOMPRAPRODUTO 			DECIMAL(10,2),
  PRIMARY KEY(NUMPEDIDOCOMPRA, CODPRODUTO),
  FOREIGN KEY(NUMPEDIDOCOMPRA) 			REFERENCES PEDIDOCOMPRA(NUMPEDIDOCOMPRA),
  FOREIGN KEY(CODPRODUTO) 					REFERENCES PRODUTO(CODPRODUTO)
);

