ALTER TABLE PRODUTOCOMPOSTO ADD QUANTIDADE DECIMAL(10,2)	NOT NULL;

ALTER TABLE UNIDADE_FEDERATIVA ADD COD_REGIAO NUMBER;
ALTER TABLE UNIDADE_FEDERATIVA ADD FOREIGN KEY (COD_REGIAO) REFERENCES REGIAO (COD_REGIAO);
ALTER TABLE UNIDADE_FEDERATIVA MODIFY COD_REGIAO NOT NULL;
