algoritmo "Círculo"
// Função :
// Autor :
// Data : 3/26/2014
// Seção de Declarações 
var
      r,a,v,c:real
inicio
      Escreva("Digite o raio da esfera:")
      leia(r)
      // Seção de Comandos
      c<-2*pi*r
      a<-pi*r^2
      v<-3/4*pi*r^3
      // Saída
      Escreval("O valor do comprimento da esfera é:",c)
      Escreval("O valor da área da esfera é:",a)
      Escreval("O valor do volume da esfera é:",v)
      
fimalgoritmo
