var k=null;"object"!==typeof JSON&&(JSON={});
(function(){function b(a){return 10>a?"0"+a:a}function d(a){c.lastIndex=0;return c.test(a)?'"'+a.replace(c,function(a){var c=q[a];return"string"===typeof c?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function f(a,c){var b,n,p,v,w=e,r,g=c[a];g&&("object"===typeof g&&"function"===typeof g.toJSON)&&(g=g.toJSON(a));"function"===typeof l&&(g=l.call(c,a,g));switch(typeof g){case "string":return d(g);case "number":return isFinite(g)?String(g):"null";case "boolean":case "null":return String(g);
case "object":if(!g)return"null";e+=h;r=[];if("[object Array]"===Object.prototype.toString.apply(g)){v=g.length;for(b=0;b<v;b+=1)r[b]=f(b,g)||"null";p=0===r.length?"[]":e?"[\n"+e+r.join(",\n"+e)+"\n"+w+"]":"["+r.join(",")+"]";e=w;return p}if(l&&"object"===typeof l){v=l.length;for(b=0;b<v;b+=1)"string"===typeof l[b]&&(n=l[b],(p=f(n,g))&&r.push(d(n)+(e?": ":":")+p))}else for(n in g)Object.prototype.hasOwnProperty.call(g,n)&&(p=f(n,g))&&r.push(d(n)+(e?": ":":")+p);p=0===r.length?"{}":e?"{\n"+e+r.join(",\n"+
e)+"\n"+w+"}":"{"+r.join(",")+"}";e=w;return p}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+b(this.getUTCMonth()+1)+"-"+b(this.getUTCDate())+"T"+b(this.getUTCHours())+":"+b(this.getUTCMinutes())+":"+b(this.getUTCSeconds())+"Z":k},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var a,c,e,h,q,l;"function"!==typeof JSON.stringify&&(c=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
q={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},JSON.stringify=function(a,b,c){var d;h=e="";if("number"===typeof c)for(d=0;d<c;d+=1)h+=" ";else"string"===typeof c&&(h=c);if((l=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return f("",{"":a})});"function"!==typeof JSON.parse&&(a=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,JSON.parse=function(b,
c){function e(a,b){var d,f,g=a[b];if(g&&"object"===typeof g)for(d in g)Object.prototype.hasOwnProperty.call(g,d)&&(f=e(g,d),void 0!==f?g[d]=f:delete g[d]);return c.call(a,b,g)}var d;b=String(b);a.lastIndex=0;a.test(b)&&(b=b.replace(a,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(b.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return d=
eval("("+b+")"),"function"===typeof c?e({"":d},""):d;throw new SyntaxError("JSON.parse");})})();
(function(b,d){"undefined"!=typeof module&&module.m?module.m=d():"function"==typeof define&&define.q?define(d):this[b]=d()})("$script",function(){function b(a,b){for(var c=0,e=a.length;c<e;++c)if(!b(a[c]))return h;return 1}function d(a,c){b(a,function(a){return!c(a)})}function f(c,e,h){function g(a){return a.call?a():u[a]}function l(){if(!--z){u[A]=1;x&&x();for(var a in s)b(a.split("|"),g)&&!d(s[a],g)&&(s[a]=[])}}c=c[q]?c:[c];var t=e&&e.call,x=t?e:h,A=t?c.join(""):e,z=c.length;setTimeout(function(){d(c,
function(c){if(c===k)return l();if(n[c])return 2==n[c]&&l();n[c]=1;a(!/^https?:\/\//.test(c)&&p?p+c+".js":c,l)})},0);return f}function a(a,b){var d=c.createElement("script"),f=h;d.onload=d.onerror=d[t]=function(){d[l]&&!/^c|loade/.test(d[l])||f||(d.onload=d[t]=k,f=1,n[a]=2,b())};d.async=1;d.src=a;e.insertBefore(d,e.lastChild)}var c=document,e=c.getElementsByTagName("head")[0],h=!1,q="push",l="readyState",t="onreadystatechange",u={},s={},n={},p;f.get=a;f.s=function(a,c,b){(function y(e){e=a.shift();
!a.length?f(e,c,b):f(e,y)})()};f.path=function(a){p=a};f.t=function(a,c,e){a=a[q]?a:[a];var h=[];!d(a,function(a){u[a]||h[q](a)})&&b(a,function(a){return u[a]})?c():!function(a){s[a]=s[a]||[];s[a][q](c);e&&e(h)}(a.join("|"));return f};f.r=function(a){f([k],a)};return f});var m=window.atinge;m||(m=window.atinge={});m.window=window;m.n=navigator.plugins;m.j=Math.floor(4294967295*Math.random());m.g="atinge_";m.isArray=function(b){var d=typeof b;return"array"==d||"object"===d&&"[object Array]"==Object.prototype.toString.call(b)};
m.e=function(b,d){var f,a,c,e,h;f=b.length&3;a=b.length-f;c=d;for(h=0;h<a;)e=b.charCodeAt(h)&255|(b.charCodeAt(++h)&255)<<8|(b.charCodeAt(++h)&255)<<16|(b.charCodeAt(++h)&255)<<24,++h,e=3432918353*(e&65535)+((3432918353*(e>>>16)&65535)<<16)&4294967295,e=e<<15|e>>>17,e=461845907*(e&65535)+((461845907*(e>>>16)&65535)<<16)&4294967295,c^=e,c=c<<13|c>>>19,c=5*(c&65535)+((5*(c>>>16)&65535)<<16)&4294967295,c=(c&65535)+27492+(((c>>>16)+58964&65535)<<16);e=0;switch(f){case 3:e^=(b.charCodeAt(h+2)&255)<<16;
case 2:e^=(b.charCodeAt(h+1)&255)<<8;case 1:e^=b.charCodeAt(h)&255,e=3432918353*(e&65535)+((3432918353*(e>>>16)&65535)<<16)&4294967295,e=e<<15|e>>>17,c^=461845907*(e&65535)+((461845907*(e>>>16)&65535)<<16)&4294967295}c^=b.length;c^=c>>>16;c=2246822507*(c&65535)+((2246822507*(c>>>16)&65535)<<16)&4294967295;c^=c>>>13;c=3266489909*(c&65535)+((3266489909*(c>>>16)&65535)<<16)&4294967295;return(c^c>>>16)>>>0};
m.o=function(){for(var b=m.n,d="",f=0;f<b.length;++f){var a=b[f];"string"==typeof a.name&&(d+=a.name);"string"==typeof a.description&&(d=d+"/"+a.description);"string"==typeof a.filename&&(d=d+"/"+a.filename);d+="\n"}return m.e(d,0).toString(16)+m.e(d,2588935699).toString(16)+m.e(d,3237188224).toString(16)};m.url=function(b){return m.local?b:window.location.protocol+"//api.atinge.com"+b};m.h=function(b){if(b==k)return b;b=b.trim();return""==b?k:b};
m.setData=function(b,d,f){f=f?"sessionStorage":"localStorage";b=m.g+b;window[f]?window[f].setItem(b,d):document.cookie=b+"="+encodeURIComponent(d)};m.getData=function(b){var d;b=m.g+b;if(window.localStorage&&(d=window.localStorage.getItem(b))||window.sessionStorage&&(d=window.sessionStorage.getItem(b)))return d;b+="=";d=document.cookie.split(";");for(var f=0;f<d.length;f++){for(var a=d[f];" "==a.charAt(0);)a=a.substring(1,a.length);if(0==a.indexOf(b))return a.substring(b.length,a.length)}return k};
m.log="undefined"!=typeof console&&console.log?console.log.bind(console,"ATINGE:"):function(){};
(function(){function b(a){this.p=a;this.global=[];this.c=[];this.a=[];this.b=k}function d(){this.f=[]}var f=window.atinge;d.prototype.addSize=function(a,c){2==a.length&&this.f.push([a,c]);return this};d.prototype.build=function(){return this.f.slice(0)};b.prototype.push=function(){for(var a=!1,c=0;c<arguments.length;c++){var b=[].concat(arguments[c]),d=b[0];"string"!=typeof d?"function"==typeof d&&d(this):(d.indexOf("@")?this.global.push(b):this.c.push(b),"request"==d&&(this.b&&(this.c.push(["tg",
this.b]),this.b=k),this.d&&(this.c.push(["slt"].concat(this.d)),this.d=k),a=!0))}a&&(this.execute(this.c),this.c=[])};b.prototype.execute=function(a){a=encodeURIComponent(JSON.stringify(this.global.concat(a)));$script(this.p+"?r="+Math.floor(1E5*Math.random())+"&cmd="+a)};b.prototype.setTargeting=function(a,c){this.b==k&&(this.b={});this.b[a]=c};b.prototype.sizeMapping=function(){return new d};b.prototype.l=function(a){if("string"==typeof a)return a;if("function"==typeof a.k)a=a.k();else if(!(a.length&&
2==a[0].length))return k;var c=0,b=0;"number"==typeof window.innerWidth?(c=window.innerWidth,b=window.innerHeight):document.documentElement&&document.documentElement.clientWidth?(c=document.documentElement.clientWidth,b=document.documentElement.clientHeight):document.body&&document.body.clientWidth&&(c=document.body.clientWidth,b=document.body.clientHeight);if(0==c||0==b)return k;a.sort(function(a,c){var b=a[1]||[],d=c[1]||[];return(2==d.length?d[0]*d[1]:0)-(2==b.length?b[0]*b[1]:0)});for(var d=0;d<
a.length;++d){var f=a[d][0][0],l=a[d][0][1];if(!(f&&f>c||l&&l>b))return a=a[d][1]||[],2==a.length?a[0]+"x"+a[1]:k}return k};b.prototype.registerSlot=function(){this.d==k&&(this.d=[]);var a={};if("string"==typeof arguments[0]){if(a={name:arguments[0]},1<arguments.length){var b=this.l(arguments[1]);b&&(a.sizes=b)}}else a=arguments[0];this.d.push(a)};b.prototype.asyncNavegg=function(a){function b(){return f.e((f.getData("pid")||"")+Math.round((new Date).getTime()/216E5),0).toString(16)}var d=f.getData("navegg_logged"),
h=f.getData("navegg_usr");if(b()!==d||!h){var q=this;window.nvg33590=new function(){this.start=function(a,d,e){"string"==typeof d&&(""!==d&&"string"==typeof e&&""!==e)&&q.push(["navegg_ids",d.replace(/:/g,"_"),e.replace(/:/g,"_")]);q.onFinish(function(d){d&&(f.setData("navegg_logged",b()),f.setData("navegg_usr",a))});$script("//navdmp.com/req?v=7&upd=1&acc=33590&id="+a+"&tit="+escape(window.document.title))};this.include=this.doSync=function(){}};$script("//navdmp.com/usr?v=7&acc=33590&new=1&wst=0",
a)}else a(),$script("//navdmp.com/req?v=7&upd=1&acc=33590&id="+h+"&tit="+escape(window.document.title))};b.prototype.onFinish=function(a){f.isArray(this.a)?this.a.push(a):a(this.a)};b.prototype.callOnFinish=function(a){if(f.isArray(this.a)){for(var b=0;b<this.a.length;++b)this.a[b](a);this.a=a}};f.i=b})();
(function(b){function d(){var d=window.atingePartner;if(b.isArray(d)){var a=new b.i(b.url("/partners/request"));window.atingePartner=a;a.push(["@ver",1]);a.push(["@bi",b.j]);var c;(c=b.getData("pid"))&&a.push(["@pid",c]);(c=b.h(document.title))&&a.push(["tl",c]);(c=b.h(document.referrer))&&a.push(["rf",c]);c=0;window.localStorage&&(c|=1);window.sessionStorage&&(c|=2);window.orientation&&(c|=4);var e;try{e=window.self!==window.top}catch(h){e=!0}e&&(c|=8);a.push(["ft",c]);a.push(["ph",b.o()]);isNaN(screen.width)||
a.push(["sww",screen.width]);isNaN(screen.height)||a.push(["swh",screen.height]);isNaN(screen.colorDepth)||a.push(["sc",screen.colorDepth]);isNaN(window.screenX)?isNaN(window.screenLeft)||a.push(["sx",window.screenLeft]):a.push(["sx",window.screenX]);isNaN(window.screenY)?isNaN(window.screenTop)||a.push(["sy",window.screenTop]):a.push(["sy",window.screenY]);e=new Date;a.push(["t",e.getTime()]);a.push(["tz",e.getTimezoneOffset()]);a.push.apply(a,d)}}b.doNotStart?b.initializer=d:d()})(window.atinge);
